### ISSUE TITLE
Is there a win-x86 version for devtunnels-cli?

### ISSUE THREAD

**Issue by ali50m** [microsoft/dev-tunnels#251]
I`d like to test a web server on a old low RAM memeory PC which is Win10 LTSB x86. 

Is there a x86 version for this great tool?

**Comment by curib** [comment]
@ali50m, no x86 version yet, but we'll keep you updated and respond here if we have any additional questions! 😃

**Comment by derekbekoe** [comment]
Thanks for the suggestion. Unfortunately we don't have plans to add a win-x86 version of the CLI.

However, since this issue was first created, we've added further options for installation - https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows#install.

Given we don't plan to take a look at this in the medium term, I'm going to be closing this issue. If we revisit this in the future, we'll re-open.
Thanks.
