### ISSUE TITLE
SDKs: Rust API library documentation and examples

### ISSUE THREAD

**Issue by JavanZhu** [microsoft/dev-tunnels#285]

**Comment by derekbekoe** [comment]
@JavanZhu The devtunnel CLI is not currently open-source and we don't have plans to open source it at this time.
Is there a specific platform/OS you're looking to create a binary for?

**Comment by JavanZhu** [comment]
> @JavanZhu The devtunnel CLI is not currently open-source and we don't have plans to open source it at this time.
> Is there a specific platform/OS you're looking to create a binary for?

Hi, @derekbekoe , I would like to run the Rust API library implementation in the repository, but I couldn't find any examples in the repository. From the documentation, I see that there are examples demonstrating the usage of the CLI program. Is there any documentation or examples available that explain how to use the Rust API library implementation? Thank you very much.

**Comment by derekbekoe** [comment]
Thanks, I've updated the title to reflect this.
SDK documentation is an area we are planning to improve in the future.
In the meantime, we're keen to learn more about your use-case for the dev tunnels Rust SDK! Feel free to reach out to us at tunnelsfeedback[@]microsoft.com.

**Comment by JavanZhu** [comment]
> Thanks, I've updated the title to reflect this. SDK documentation is an area we are planning to improve in the future. In the meantime, we're keen to learn more about your use-case for the dev tunnels Rust SDK! Feel free to reach out to us at tunnelsfeedback[@]microsoft.com.

use-case:
We have deployed an SFTP service on a Linux server using openssh-portable to provide file sharing services to customers. However, due to certain limitations, we cannot use TCP/IP and can only share files through file sharing protocols based on HTTP/HTTPS, such as WebDAV. WebDAV requires a complete replacement of the existing program, but our goal is to keep the existing program as unchanged as possible to achieve this goal. We found that dev-tunnel provides SSH through WebSocket, which is in line with our requirements as WebSocket protocol is implemented on top of HTTP protocol. Therefore, we want to use the devtunnel Rust API to provide an SSH tunnel for the existing openssh-portable program.

So, we want to run the Rust API SDK demo to evaluate whether this is feasible. If there are any unclear or questionable points in my description, please feel free to ask me. Thank you.

**Comment by jasongin** [comment]
My understanding is you want to use a dev tunnel to forward a TCP port from the host (where the SFTP service is running) to a client system, and then presumably there is some client software that can connect to that forwarded port on its `localhost` using the SFTP protocol.

At this time, that's not possible to do using the dev tunnels Rust API, because it lacks the client-side port forwarding capability. So far only host-side port forwarding is implemented (because it was developed primarily for [VS Code Server](https://code.visualstudio.com/docs/remote/vscode-server)). We may add client-side forwarding to the Rust SDK later but there is no timeline for that now.

The C# and TypeScript APIs do have both host- and client-side port forwarding capability. So you could use either of those. Or the [`devtunnel` command-line tool](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands) would be easier.

I should point out also that the scenario you describe, exposing an SFTP server to customers, is not really what the dev tunnels service is meant for, so you won't find much support or documentation for that. Dev tunnels are designed for and optimized for _developer_ scenarios such as developing web hooks and connecting to remote development resources, and the SDK code in this repo is designed to support integration with developer applications such as IDEs and command-line developer tools.

**Comment by JavanZhu** [comment]
> My understanding is you want to use a dev tunnel to forward a TCP port from the host (where the SFTP service is running) to a client system, and then presumably there is some client software that can connect to that forwarded port on its `localhost` using the SFTP protocol.
> 
> At this time, that's not possible to do using the dev tunnels Rust API, because it lacks the client-side port forwarding capability. So far only host-side port forwarding is implemented (because it was developed primarily for [VS Code Server](https://code.visualstudio.com/docs/remote/vscode-server)). We may add client-side forwarding to the Rust SDK later but there is no timeline for that now.
> 
> The C# and TypeScript APIs do have both host- and client-side port forwarding capability. So you could use either of those. Or the [`devtunnel` command-line tool](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands) would be easier.
> 
> I should point out also that the scenario you describe, exposing an SFTP server to customers, is not really what the dev tunnels service is meant for, so you won't find much support or documentation for that. Dev tunnels are designed for and optimized for _developer_ scenarios such as developing web hooks and connecting to remote development resources, and the SDK code in this repo is designed to support integration with developer applications such as IDEs and command-line developer tools.

Hi @jasongin Thank you very much for your detailed explanation and response. By the way, it would be very helpful to have a demo showing how to use these RUST APIs. I am looking forward to seeing this part being improved in the future. Thank you.
