### ISSUE TITLE
Unexpected error during devtunnel login on Windows

### ISSUE THREAD

**Issue by greggdavenport** [microsoft/dev-tunnels#314]
I have yet to be able to login. Always get this error and then PowerShell freezes up:

Unknown Status: Unexpected
Error 0xffffffff80070520
Context: Unexpected exception while waiting for accounts control to finish: '(pii)'
Tag: 0x1f7d734b (error code -2147023584) (internal error code 528315211)

**Comment by jasongin** [comment]
@greggdavenport Does that error come from trying to use the `devtunnel login` command?

What version of the tool do you have? (`devtunnel --version`)

I'm not sure what is causing that error, but you can try `devtunnel login -d` to use the device code login flow, that might work better since it does not rely on local accounts UI controls.

**Comment by greggdavenport** [comment]
Thanks @jasongin ,
Yes it is when I try `devtunnel login`.

For `devtunnel -version` I get:
Tunnel CLI version: 1.0.882+30dac05290

Tunnel service URI        : https://global.rel.tunnels.api.visualstudio.com/
Tunnel service version    : 1.0.915.14170 (5a37895e76; 2023-09-19 18:02:07Z)
Tunnel service cluster    : usw2

Using `devtunnel login -d` works beautifully, thank you.

**Comment by derekbekoe** [comment]
Closing as it looks like `devtunnel login -d` unblocked log in.

**Comment by IMRAN-5740** [comment]
its also work for me thanks dear
