### ISSUE TITLE
Client cannot make API calls when running in Dev Tunnel

### ISSUE THREAD

**Issue by danheinz** [microsoft/dev-tunnels#355]
I'm trying to use Dev Tunnels with my Blazor .NET client application.  I also have a REST API project (.NET 7) that the client utilizes.
The API is hosted in Azure, but I cannot get the client to make successful API requests when the client is running in a Dev Tunnel.
In Fiddler, I see the client making HTTP OPTIONS /protected/Provider HTTP/1.1 requests, but no other HTTP verbs are used in any requests.

I updated the CORS settings for the API to include the client dev tunnel URL (the actual settings file does not have any x 'd-out data).
"CorsPolicySettings": {
  "Origins": [
    "https://localhost:7094",
    "https://xxxxxxxx-7094.use2.devtunnels.ms/"
  ]
},

What am I missing?  

I set up a dev tunnel for the API running locally on my machine, and I can connect to it with the client just fine when the client is not using a dev tunnel.  But when I switch the client to a dev tunnel, I have the same issue where no API requests are made - just the HTTP OPTIONS.

Here is an example header from an HTTP request:

Request URL:
https://xxxxxxxxxxxxxxxxxx.azurewebsites.net/protected/Provider
Request Method: OPTIONS
Status Code: 204 No Content
Remote Address: 127.0.0.1:8888
Referrer Policy: same-origin

**Comment by derekbekoe** [comment]
So the client (Blazor application) is running locally on `localhost:7094` and also on the dev tunnel at `https://xx-7094.use2.devtunnels.ms`. The API project is running on Azure at `https://xx.azurewebsites.net/protected/Provider`.

When you visit `https://xx-7094.use2.devtunnels.ms`, the client is unable to make the request to `https://xx.azurewebsites.net/protected/Provider` but it works when using the client running on `localhost:7094`.

Is that correct?

If so, it may be that the updated CORS settings are not taking effect on your Azure Website.
Right now, I don't see how dev tunnels would be involved since the request is being made to `https://xx.azurewebsites.net/protected/Provider`.

**Comment by danheinz** [comment]
API app using dev tunnel/WebAssembly app using dev tunnel and both running locally:
    Access API from WebAssembly app: fails
    Access API from Postman: succeeds
The API app includes the dev tunnel URL for the WebAssembly dev tunnel.

I have tried also only running the WebAssembly app dev tunnel locally, and having it connect to the API when it is hosted in Azure, but I have the same issue.  The CORS settings do not change when our pipeline builds and deploys the API.

The CORS policy is (x's replacing actual values):

`  "CorsPolicySettings": {
    "Origins": [
      "https://localhost:7094",     <-------The WebAssembly when run locally without a dev tunnel (this works)
      "https://xxxx-xxxx-xxxxxxx.1.azurestaticapps.net",
      "https://xxxxxx.com",
      "https://xxxxxxxx-7094.use2.devtunnels.ms/"   <-----The WebAssembly dev tunnel
    ]
  },`

**Comment by danheinz** [comment]
Thank you for looking at this.  We have resolved the issue.
I was able to add a wildcard CORS entry in my appsettings for the API and things worked (https://*devtunnels.ms/).  It looks like this:

"CorsPolicySettings": {
  "Origins": [
    "https://localhost:7094",
    "https://*devtunnels.ms/"
  ]
},
