### ISSUE TITLE
Organization controls for Dev Tunnels

### ISSUE THREAD

**Issue by cybernot** [microsoft/dev-tunnels#398]
We have developers starting to use these tunnels, we see this as a threat to our security. What we'd like to know is whether we have a way to:

(1) Prevent developers from using the unsafe options for the tunnel, like public and permanent
(2) Enforce that developers use the safe options for the tunnel, like private and temporary
 

Is there a central place where we can configure (1) and/or (2) in our ADO or GitHub tenants ? If we cannot do (1) and (2), what other controls do we have to secure this from a central point in an organization?

Thanks

**Comment by derekbekoe** [comment]
Thanks for the feature request.

We have plans for group policy controls. This is tracked by https://github.com/microsoft/dev-tunnels/issues/321.
Beyond that, we don't have plans for deeper integrations with ADO or GitHub and do not have plans to add this in the short or medium term.

If you're interested in the group policy controls, please follow the linked issue.
Otherwise, I'll be closing this as we aren't planning to add the other controls at this point in time.
