### ISSUE TITLE
Request more ports per tunnel

### ISSUE THREAD

**Issue by remokeitel** [microsoft/dev-tunnels#437]
Hi,

I need more ports per tunnel, please. I want to use the dev tunnels with a .NET Aspire application with a lot of microservices. I think I need max. 30 ports per tunnel. Could you please increase the limit for my VS account.

Thanks and best
Remo

**Comment by derekbekoe** [comment]
Hi - We're not taking requests to increase the number of ports per tunnel at this time.
We allow multiple simultaneous tunnels so that could be an option to get more overall active ports.
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#dev-tunnels-limits
