### ISSUE TITLE
Why some ports can be accessed with :PORT and others cannot

### ISSUE THREAD

**Issue by servefast-cto** [microsoft/dev-tunnels#450]
Hi,

as you can see ports 5000,5001,8080 can be accessed with :5000 :5001 :8080 notation while other ports can not. Is there a reason for that for example limitation on amount of ports being available like that ?

Example:
```
Hosting port: 5000
Connect via browser: https://XXXXXX.euw.devtunnels.ms:5000, https://XXXXXX-5000.euw.devtunnels.ms
Inspect network activity: https://XXXXXX-5000-inspect.euw.devtunnels.ms
Hosting port: 5001
Connect via browser: https://XXXXXX.euw.devtunnels.ms:5001, https://XXXXXX-5001.euw.devtunnels.ms
Inspect network activity: https://XXXXXX-5001-inspect.euw.devtunnels.ms
Hosting port: 8080
Connect via browser: https://XXXXXX.euw.devtunnels.ms:8080, https://XXXXXX-8080.euw.devtunnels.ms
Inspect network activity: https://XXXXXX-8080-inspect.euw.devtunnels.ms
Hosting port: 9000
Connect via browser: https://XXXXXX-9000.euw.devtunnels.ms
Inspect network activity: https://XXXXXX-9000-inspect.euw.devtunnels.ms
Hosting port: 9099
Connect via browser: https://XXXXXX-9099.euw.devtunnels.ms
Inspect network activity: https://XXXXXX-9099-inspect.euw.devtunnels.ms
Hosting port: 9199
Connect via browser: https://XXXXXX-9199.euw.devtunnels.ms
Inspect network activity: https://XXXXXX-9199-inspect.euw.devtunnels.ms
Hosting port: 9998
```

**Comment by derekbekoe** [comment]
Here is the list of ports that support that feature:
1027, 1111, 1234, 1313, 3000, 3001, 4000, 4200, 5000, 5001, 5173, 5174, 5500, 5555, 6006, 7016, 7027, 7038, 7092, 7110, 7137, 7233, 7258, 7777, 7860, 8000, 8050, 8080, 8081, 8089, 8888, 9291

Due to some limitations, we were not able to make this feature available for every single port.
The ports in this list were selected based on the most commonly used ports.

**Comment by derekbekoe** [comment]
Closing this as stale and the list of ports have been provided above. At this time, we have no plans to modify that list of ports.
