### ISSUE TITLE
Constantly getting 404 totally randomly for angular chunks 

### ISSUE THREAD

**Issue by Dzivo** [microsoft/dev-tunnels#469]
GET https://XXXXX-5000.euw.devtunnels.ms/chunk-IUSG6QPW.js net::ERR_ABORTED 404 (Not Found)

This happens regulary it works for 10 minutes and then stops working

**Comment by derekbekoe** [comment]
Can you send us sample request ids and timestamps for those 404s?

**Comment by Dzivo** [comment]
[s5198zdw-5000.euw.devtunnels.ms-1722403857042.log](https://github.com/user-attachments/files/16436678/s5198zdw-5000.euw.devtunnels.ms-1722403857042.log)

Is this ok ?

**Comment by Dzivo** [comment]
[network-log.zip](https://github.com/user-attachments/files/16436772/network-log.zip)

This is from an inspect page for another request that failed

**Comment by derekbekoe** [comment]
Our logs indicate that the 404s were returned by the user application (i.e. your server) and it was that status code that our service forwarded to your client. Also, for the HTTP responses in the provided HAR file, the value for the `X-Powered-By` header is `Express` which would also come from your server, not the Dev Tunnels infrastructure/service.

It may that your client-side browser cache is requesting files that have since been removed/renamed on your server. For example, in the HAR file, there's a `GET` request to `http://s5198zdw-5000.euw.devtunnels.ms/chunk-EC5ID3OO.js` that contains the caching headers `if-modified-since: Wed, 31 Jul 2024 05:29:46 GMT` and `if-none-match`. The 404 response was sent at `Wed, 31 Jul 2024 05:41:44 GMT`. If you're using something like webpack, it may be producing files with different file names during development as your code or imports get updated.

A solution here may be to disable browser caching, e.g. via Browser DevTools.
